### ISSUE TITLE
Optimization is not working

### ISSUE THREAD

**Issue by chethanparameshwara** [ImperialCollegeLondon/event_emin_ros#1]
Hi,

Thanks for the great work!! I could successfully compile the codebase on Ubuntu 18, ROS melodic. When I run ```rosrun event_emin_ros affinity camera_info:=/dvs/camera_info events:=/dvs/events```

I am getting zero var values. 

```
header:
  seq: 836
  stamp:
    secs: 1468940052
    nsecs: 701401018
  frame_id: ''
vars: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

Do you know why the optimization is not working?
